### ISSUE TITLE
I want to see the animation in Qtenv for scenario

### ISSUE THREAD

**Issue by yzy26353520** [tkn-tub/serpentine-env#6]
# Environment
I have compiled _serpentine-env_ and run `veins_launchd -vv`
Folder structure like this:
![图片](https://user-images.githubusercontent.com/83323222/170409293-0da2e62f-7e92-4556-9438-95e1f73ab055.png)

# Appearance
-  python file works fine：
```
david@david-PC:~/workspace/serpentine-env-master/examples$ ./random_agent.py 
Number of steps taken: 3680
Mean reward: 0.6655652135190473
```

-  After running `./run` in the _scenario_ folder, Qtenv gets stuck after selecting the configuration file：
![图片](https://user-images.githubusercontent.com/83323222/170406714-42b8d548-8f1f-437f-8737-96274d4e2597.png)
- But doing this in the _veins_ and _veins-vlc_ folder works fine：
`david@david-PC:~/workspace/serpentine-env-master/lib/veins/examples/veins$ ./run`
`david@david-PC:~/workspace/serpentine-env-master/lib/veins-vlc/examples/veins-vlc$ ./run `
- However the configuration option "DriveLslc" runs with an error：
![图片](https://user-images.githubusercontent.com/83323222/170407919-92095f78-5117-48a3-9c0d-aa0ee5cf0ee3.png)

# The Effect I Want #
1. I want to see the animation in Qtenv for _scenario_ folder
`david@david-PC:~/workspace/serpentine-env-master/scenario$ ./run `
2. How can I get start to build my simulation environment？ I want to study reinforcement learning for Platoon([Plexe](http://plexe.car2x.org/))

Thanks for your answer

**Comment by dbuse** [comment]
Hi @yzy26353520 
the OMNeT++ GUI gets "stuck" after running `./run` in the `scenario` directory, because it is waiting for an agent to connect to it.

When you only run the Veins/OMNeT++ portion (via the `./run` script), there is no agent to perform any action. In contrast, when you run a veins gym environment from python (e.g., via `./random_agent.py`), it both launches the Veins/OMNeT++ simulation (normally without a GUI) *and* runs the agent, which connects to it and sends actions.

Please check https://github.com/tkn-tub/veins-gym#starting-veins-simulations-separately for how to connect an agent to a separately started Veins simulation.

**Comment by yzy26353520** [comment]
Thank you. It works well. Change _random_agent.py_ 's kwargs and run:
```
david@david-PC:~/workspace/serpentine-env-master/scenario$ ./run 
david@david-PC:~/workspace/serpentine-env-master/scenario$ ./run -u Cmdenv '--*.gym-connection.port=5555'
david@david-PC:~/workspace/serpentine-env-master/examples$ python3.8 random_agent.py 
```
