### ISSUE TITLE
About the changes in omnetpp.ini file

### ISSUE THREAD

**Issue by serapergun** [tkn-tub/serpentine-env#8]
Hello,

I am changing ini file to see the changes.
But whatever I do, the serpentine scenario runs as if default mode.

What am I doing wrong?
For example I change *.node[*].applType = "SerpentineApp" to some other AppFile, nothing changes.
Or I change the network= SerpentineScenario, nothing changes too.

I would be very appreciate if you show me the way.

Regards

**Comment by dbuse** [comment]
Hi @serapergun,

I am having some trouble understanding precisely what your problem is. 
What I understand is: You want to modify the `omnetpp.ini` configuration file (e.g., using a different application type) but the simulation appears unchanged.

Maybe, you are having issues with how configuration overwriting works in OMNeT++ (best match wins) [see the manual](https://doc.omnetpp.org/omnetpp/manual/#sec:config-sim:precedence-of-entries).

For debugging, it might be helpful to run the Veins/OMNeT++ simulation separately and with the QtEnv GUI enabled, so you can inspect the details. See [the Readme of veins-gym on how to do that](https://github.com/tkn-tub/veins-gym#starting-veins-simulations-separately).
Aside from that, I would need more description or (even better) an example of a changed `omnetpp.ini` file to understand what might be the issue.

Best,
Dominik

**Comment by serapergun** [comment]
Hi @dbuse,
Firstly, thank you for quick replay. 
You understood me exactly right.
I wrote a new application type about decision making and a new car module.I want to use them.

For example I changes as follow:

network = HeteroScenario
*.manager.moduleType = "serpentine.HeteroGenericNode"
*.node[*].applType = "DecisionMakerApp"
*.gym_connection.action_space = "gym.spaces.Discrete(2)"

In random_agent file, I added this line:
 "user_interface": "Qtenv",

thanks to this line, I saw GUI perfectly. And also the results of rewards and observations in Console.

However, I could not see the effects of my added files.

Regards,
Serap

**Comment by dbuse** [comment]
So the simulation still uses the previous `network`/`moduleType`/`applType`/etc.?
Did you change the lines in the `omnetpp.ini` file or add your own at the bottom (potentially in a different config)?

Maybe providing the full diff of the `omnetpp.ini` file or pushing your changes to github could help. There is many places where these issues may be coming from.

**Comment by serapergun** [comment]
@dbuse 

I just changed the 4 lines in the omnetpp.ini file (in the previous comment) which is under serpentine-env/scenario.

I add project reference as SimulTE. And I used the nodes from there by importing as:
import lib.veins.src.veins.nodes.HeteroNodeCar;
![Screenshot from 2022-06-17 15-56-49](https://user-images.githubusercontent.com/11541586/174312954-c1192f75-9fbb-41b8-a024-106a4d68a9aa.png)

**Comment by dbuse** [comment]
So in the GUI, if you clock on the `node[0]` element in the canvas and check its configuration in the explorer on the left, its `applType` is still the default and not your `"DecisionMakerApp"`?

Again, this is hard do tell from what and how you have posted it.

Though this seems to be a problem located only within the Veins/OMNeT++ side of the system. So you could run your Veins scenario without an agent and inspect/debug it to investigate the error.

**Comment by andresq99** [comment]
Hello
I am trying to replicate the serpentine-env code using Ubuntu 18.04 virtual machine. The requirements installed were Sumo 1.6.0, Omnet++ 5.6.2, and protoc version libprotoc 3.5.0. I have some problems with protoc version. The message is "This file was generated by an older version of protoc which is". Can you tell me the protoc version that you use to test and implement the serpentine env.

Regards, Andres

**Comment by dbuse** [comment]
Hi @andresq99 
for our demo environment in the docker container, we successfully used the following version
```bash
$ docker run -it --rm  ghcr.io/tkn-tub/veins-gym:0.3.3 protoc --version
libprotoc 3.6.1
```

**Comment by serapergun** [comment]
I forgot to write here.
Whenever I made a change in ini file about gym, I figure out that it should be run snakemake -jall to set environment.
I'm sharing it in case if there is someone who needs it and lost their months like me.
Thanks,
